//! What a node implements.
//!
//! One trait per specification, named alike. Which trait a method lives on
//! **is** its classification, so nothing needs a table saying which names
//! belong to which protocol — and a request on 23194 is checked against
//! `methods` while one on 23198 is checked against `control`, structurally
//! rather than by a branch that could pick wrong.
//!
//! Every method defaults to `NOT_IMPLEMENTED`, so a node writes only what
//! it serves. `methods()` has **no** default: it is generated by
//! `#[nostr_ln::service]` from the impl block, so forgetting the macro is a
//! compile error rather than a node that advertises nothing and denies
//! everything at runtime.

use std::future::Future;
use std::pin::Pin;

use nostr::key::PublicKey;
use serde_json::Value;

use crate::nnc::{methods::*, NncError};
use crate::nwc::methods::*;

/// A boxed future, so the traits stay object-safe.
pub type Fut<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// The result of preparing an operation.
///
/// Carries the cost **and the selection** — the route, the feerate, the
/// unsigned transaction. `execute` acts on that choice rather than making
/// it again, which is how the two could otherwise differ.
///
/// See [nostr-ln#1](https://github.com/DarkWebDivingClub/nostr-ln/issues/1).
pub struct Prepared {
    /// What this will cost, in satoshis. Checked against the quota before
    /// anything moves, and committed afterwards unchanged.
    ///
    /// It is also a **budget**: a payment that retries over another route
    /// must stay within it.
    pub cost_sats: u64,
    /// Whatever the node needs to carry from `prepare` to `execute`.
    pub selection: Box<dyn std::any::Any + Send>,
}

impl Prepared {
    /// An operation that costs nothing and needs no selection — the
    /// fourteen NNC methods that read rather than spend.
    pub fn free() -> Self {
        Self { cost_sats: 0, selection: Box::new(()) }
    }

    /// An operation with a cost and something to carry.
    pub fn new<S: std::any::Any + Send>(cost_sats: u64, selection: S) -> Self {
        Self { cost_sats, selection: Box::new(selection) }
    }
}

impl std::fmt::Debug for Prepared {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Prepared").field("cost_sats", &self.cost_sats).finish_non_exhaustive()
    }
}

/// Who is asking, and what they asked.
#[derive(Debug, Clone, Copy)]
pub struct Caller<'a> {
    /// The controller's pubkey — the key a grant names.
    pub controller: &'a PublicKey,
    /// The id of the request event.
    ///
    /// A handler needs this to tag the deferred result of an asynchronous
    /// command: NIP-XX makes the `e` tag a MUST there, and it is what lets
    /// a client tie an outcome to the command that caused it — two
    /// `open_channel` commands to the same peer are otherwise
    /// indistinguishable.
    ///
    /// `None` when the pipeline is driven without a transport, as in unit
    /// tests.
    pub request_id: Option<nostr::event::EventId>,
}

macro_rules! typed_methods {
    ($( $(#[$m:meta])* $fn_name:ident($req:ty) -> $res:ty ),* $(,)?) => {
        $(
            $(#[$m])*
            fn $fn_name<'a>(&'a self, _request: $req, _caller: Caller<'a>) -> Fut<'a, Result<$res, NncError>> {
                Box::pin(async move { Err(NncError::not_implemented(stringify!($fn_name))) })
            }
        )*
    };
}

/// NIP-XX. A node that can be administered.
pub trait ControlService: Send + Sync {
    /// What this node implements. **Generated** by `#[nostr_ln::service]`.
    fn methods(&self) -> &'static [&'static str];

    typed_methods! {
        /// List this node's channels.
        list_channels(ListChannelsRequest) -> ListChannelsResponse,
        /// Open a channel. Acknowledged, not completed.
        open_channel(OpenChannelRequest) -> OpenChannelResponse,
        /// Close a channel. Acknowledged, not completed.
        close_channel(CloseChannelRequest) -> CloseChannelResponse,
        /// List peers.
        list_peers(ListPeersRequest) -> ListPeersResponse,
        /// Connect to a peer.
        connect_peer(ConnectPeerRequest) -> ConnectPeerResponse,
        /// Disconnect from a peer.
        disconnect_peer(DisconnectPeerRequest) -> DisconnectPeerResponse,
        /// Read fee policy.
        get_channel_fees(GetChannelFeesRequest) -> GetChannelFeesResponse,
        /// Set fee policy.
        set_channel_fees(SetChannelFeesRequest) -> SetChannelFeesResponse,
        /// Forwarding history.
        get_forwarding_history(GetForwardingHistoryRequest) -> GetForwardingHistoryResponse,
        /// HTLCs in flight.
        get_pending_htlcs(GetPendingHtlcsRequest) -> GetPendingHtlcsResponse,
        /// Find routes.
        query_routes(QueryRoutesRequest) -> QueryRoutesResponse,
        /// List graph nodes.
        list_network_nodes(ListNetworkNodesRequest) -> ListNetworkNodesResponse,
        /// Graph statistics.
        get_network_stats(GetNetworkStatsRequest) -> GetNetworkStatsResponse,
        /// One graph node.
        get_network_node(GetNetworkNodeRequest) -> GetNetworkNodeResponse,
        /// One graph channel.
        get_network_channel(GetNetworkChannelRequest) -> GetNetworkChannelResponse,
        /// Sign with the node's Lightning identity key.
        sign_message(SignMessageRequest) -> SignMessageResponse,
    }

    /// Select a route or a feerate and say what this will cost.
    ///
    /// **Nothing moves here.** The pipeline checks the returned cost
    /// against the quota before calling `execute`, and passes the same
    /// `Prepared` back, so the selection is not made twice.
    ///
    /// Defaults to free, which is correct for the fifteen NNC methods that
    /// do not spend — only `open_channel` does.
    fn prepare<'a>(&'a self, _method: &'a str, _params: &'a Value, _caller: Caller<'a>)
        -> Fut<'a, Result<Prepared, NncError>>
    {
        Box::pin(async move { Ok(Prepared::free()) })
    }
}

/// NIP-47. A node with a wallet.
///
/// Typed over [`crate::nwc`] — published NIP-47 core, plus the extensions
/// this crate implements. A node implements the methods it serves and
/// inherits `NOT_IMPLEMENTED` for the rest, exactly as
/// [`ControlService`] works.
///
/// Until mission 18.1 this was a single `call(method, params, caller)`
/// forwarding a string, and the cost was not only ugliness:
/// `#[nostr_ln::service]` reads one entry per function in the impl block
/// and excludes `call`, so it generated an **empty** method list with no
/// error, and a wallet published kind `13194` advertising nothing.
pub trait WalletService: Send + Sync {
    /// What this node implements. **Generated** by `#[nostr_ln::service]`.
    fn methods(&self) -> &'static [&'static str];

    typed_methods! {
        /// Pay a BOLT11 invoice.
        pay_invoice(PayInvoiceRequest) -> PayInvoiceResponse,
        /// Create an invoice.
        make_invoice(MakeInvoiceRequest) -> MakeInvoiceResponse,
        /// Look one up.
        lookup_invoice(LookupInvoiceRequest) -> LookupInvoiceResponse,
        /// The wallet's balance.
        get_balance(GetBalanceRequest) -> GetBalanceResponse,
        /// What the wallet is and does.
        get_info(GetInfoRequest) -> GetInfoResponse,
        /// Send an on-chain payment. See `nwc-onchain.md`.
        pay_onchain(PayOnchainRequest) -> PayOnchainResponse,
    }

    /// As [`ControlService::prepare`].
    ///
    /// A wallet has more use for this than a node does: `pay_invoice` and
    /// `pay_onchain` both spend, and the quota is checked against what
    /// this returns **before** either runs.
    fn prepare<'a>(&'a self, _method: &'a str, _params: &'a Value, _caller: Caller<'a>)
        -> Fut<'a, Result<Prepared, NncError>>
    {
        Box::pin(async move { Ok(Prepared::free()) })
    }
}
