//! Proc macros for `nostr-ln`.
//!
//! A separate crate because Rust requires proc macros to be, and re-exported
//! by `nostr-ln` so consumers write `#[nostr_ln::service]` and never name
//! this one.

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, ImplItem, ItemImpl};

/// Generate `methods()` from the method names in an impl block.
///
/// ```ignore
/// #[nostr_ln::service]
/// impl ControlService for MyNode {
///     fn list_channels(..) { .. }
///     fn list_peers(..) { .. }
/// }
/// // emits: fn methods(&self) -> &'static [&'static str] {
/// //     &["list_channels", "list_peers"]
/// // }
/// ```
///
/// **A node cannot lie about what it implements**, because the list is not
/// written by hand. And because the trait's `methods()` has no default,
/// forgetting this macro is a compile error rather than a node that
/// advertises nothing and denies everything at runtime.
///
/// `prepare` is excluded: a pipeline hook, not a method a controller can
/// invoke. `call` is excluded for the same reason and is now vestigial —
/// no trait in this crate has one since 18.1 typed `WalletService`.
///
/// # It serves both traits
///
/// `ControlService` has sixteen typed methods and `WalletService` has six,
/// so both are read the same way and both get a generated list.
///
/// It did not, until 18.1. `WalletService` had a single `call` entry point
/// rather than one function per method, so there was nothing in the impl
/// block to read and this macro emitted an **empty list with no error** —
/// a wallet that compiled and advertised nothing. `tests/transport.rs`
/// asserts the empty case now, because it is the one that used to pass
/// silently for every wallet.
#[proc_macro_attribute]
pub fn service(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let mut block = parse_macro_input!(item as ItemImpl);

    // `prepare` is a pipeline hook and `call` is a dispatch entry point.
    // Neither is a method a controller can invoke, and advertising one
    // would offer something nobody can call.
    const NOT_A_METHOD: [&str; 3] = ["prepare", "methods", "call"];

    let names: Vec<String> = block
        .items
        .iter()
        .filter_map(|item| match item {
            ImplItem::Fn(f) => {
                let name = f.sig.ident.to_string();
                (!NOT_A_METHOD.contains(&name.as_str())).then_some(name)
            }
            _ => None,
        })
        .collect();

    if block
        .items
        .iter()
        .any(|i| matches!(i, ImplItem::Fn(f) if f.sig.ident == "methods"))
    {
        return syn::Error::new_spanned(
            &block.self_ty,
            "`methods()` is generated by #[nostr_ln::service]; remove the hand-written one, \
             which can disagree with what this impl actually provides",
        )
        .to_compile_error()
        .into();
    }

    let generated: ImplItem = syn::parse_quote! {
        fn methods(&self) -> &'static [&'static str] {
            &[#(#names),*]
        }
    };
    block.items.push(generated);

    quote!(#block).into()
}
